# Generated by Django 2.0.4 on 2018-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='field',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
