# Generated by Django 2.0.4 on 2018-05-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180508_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='field',
        ),
    ]
